package at.jku.cps.travart.core.cli;

public enum TransformationResult {
	FAILED_SERIALIZATION,
	TIMEOUT_SERIALIZATION,
	FAILED_DESERIALIZATION,
	TIMEOUT_DESERIALIZATION,
	FAILED_TRANSFORMATION,
	TIMEOUT_TRANSFORMATION,
	FAILED_UNKNOWN,
	TIMEOUT_UNKNOWN,
	SUCCESS
}
